// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyCopyright("Copyright © 2016 - DevArtist")]
[assembly: AssemblyVersion("1.0.2016.16")]
[assembly: AssemblyFileVersion("1.0.2016.16")]
